### ISSUE TITLE
Cross domain problem

### ISSUE THREAD

**Issue by stiekel** [jitsi/jicofo#224]
I need to use jitsi in my webapp, and the webapp was served on different server, if I call jitsi from the webapp, the http-bind return cross domain problem.

![jicofo cross domain problem](https://i.imgur.com/ioRuWsT.png)
![jicofo cross domain netowrk tab](https://i.imgur.com/o8BfU77.png)

in real world, the Jicofo and client may served on multiple servers, Can we set the jicofo to support CORS as default? or anyone can tell me how to set the jicofo support cross domain?

**Comment by damencho** [comment]
This is not jicofo, this is jitsi-videobridge that is serving jitsi-meet web app using jetty.

There is no option currently to change cross-origin. 
In order to add it you need to modify where the bosh servlet is initialized:
https://github.com/jitsi/jitsi-videobridge/blob/c6acc4aea85c7984ab713ad19d54bc0fc8ac0aa4/src/main/java/org/jitsi/videobridge/rest/PublicRESTBundleActivator.java#L220
Something like the solution described here:
https://stackoverflow.com/questions/29969996/set-access-control-allow-origin-in-jetty
And of course, it needs adding the maven artifact containing CrossOriginFilter:
  <groupId>org.eclipse.jetty</groupId>
    <artifactId>jetty-servlets</artifactId>

**Comment by damencho** [comment]
This is a jitsi-videobridge issue.
But what are you trying to achieve, having jvb and jicofo on different machines? Having multiple bridges?
I suppose, there are different solutions for your problem that can be implemented without changing the code for any of the components.

**Comment by stiekel** [comment]
Thanks so much, We want to add video conference in webapp with jitsi, in my first demo, the jvb and jicofo are in same server, but the webapp served on other machine, so i need jitsi support CORS.

I will check the jvb document, thank you @damencho .

**Comment by bgrozev** [comment]
> Thanks so much, We want to add video conference in webapp with jitsi, in my first demo, the jvb and jicofo are in same server, but the webapp served on other machine, so i need jitsi support CORS.

I don't think there's any need for CORS in any of the jitsi components. The web-app only communicates (via http) with prosody, and we use a proxy for "/http-bind" instead.

**Comment by stiekel** [comment]
@bgrozev when i request /http-bind , it response with Access Cross Domain Origin error.

**Comment by stiekel** [comment]
@bgrozev And after i config nginx with [this guide](https://github.com/jitsi/jitsi-meet/blob/master/doc/manual-install.md#install-nginx), Nginx response with `BOSH-Connection failed: host-unknown` .
![BOSH-Connection failed: host-unknown](https://i.imgur.com/xQ9KerX.png)

**Comment by bgrozev** [comment]
Look at the request in the "network" tab.

**Comment by bgrozev** [comment]
> I've tried building a new jitsi-videobridge with a CrossOriginFilter adding those headers in, but the bridge just hangs the moment that filter is added to the servletContextHandler.

Did you use this patch? https://github.com/jitsi/jitsi-videobridge/pull/675

**Comment by thedracle** [comment]
@bgrozev, That worked great, thankyou!

**Comment by raghbendranayak** [comment]
Hi Guys,
I have installed Jitsi meet at my own server and its working fine but My requirement is something below
User A will create an account with us in order to access live streaming classes.
Teaching class
User can chat (text)
User sets up their camera
When class begins: User’s main view is the presenter
User can still chat with group
User can receive help from the Support Instructor (SI)
User can only see the main presenter not all joined users also can hear to main presenter not all users.

Support Instructors need to enter the class management dashboard
SI can chat (text) to users
SI can talk to user through audio – One at a time and only that one user can hear the audio of the SI.

Is this possible in Jitsi meet and where I need to customization because when I install it I got only Jitsi meet code.

I follow this video to install jitsi meet.
https://www.youtube.com/watch?v=8KR0AhDZF2A

Please help me or provide some guidance on same so that I can achieve this.

**Comment by bgrozev** [comment]
Probably outdated, re-open if necessary
