### ISSUE TITLE
Reservation is not revoked when conference ends

### ISSUE THREAD

**Issue by paulvt** [jitsi/jicofo#39]
The reservation system REST API documentation mentions the following about conference (reservation) deletion: "Jicofo deletes conferences in the reservation system in two cases. First when all users leave XMPP Multi User Chat room. Second when conference duration limit is exceeded."

I am only experiencing the latter.  With the duration set to 10 minutes, the conference is never deleted before the 10 minutes expire, even if everyone leaves within the minute.

(I see no call to `deleteConference` except from within the `ConferenceExpireTask`.)

**Comment by paweldomas** [comment]
Hi ! Thanks for the report ! Not sure when we'll have the time to fix the issue, but PR fixing it would be welcome !

**Comment by paweldomas** [comment]
Actually it should be called from here as well:
https://github.com/jitsi/jicofo/blob/master/src/main/java/org/jitsi/jicofo/FocusManager.java#L368

**Comment by paulvt** [comment]
Are you sure? Because the `ConferenceExpireTask` class of `RESTReservations` already calls `focusManager.destroyConference()` which then in turn would call `RESTReservation.destroyConference()` again. Seems a bit kludgy to me? Isn't is possible to hook it up somewhere in the `FocusComponent`, which already does the `createConference()` call and has a reference to the reservation system.

**Comment by paulvt** [comment]
I've been digging through the code, but I see that the reservation system does a `focusManager.setFocusAllocationListener(this)` when started.  The `onFocusDestroyed` method on the reservation system thus already should handle conference destruction and deregistration.  However, it seems that the `AbstractAuthAuthority`, and thus the `XMPPDomainAuthAuthority` that we are using, also does a `focusManager.setFocusAllocationListener(this)`! Aren't these calls overwriting each other's listening objects?

**Comment by paweldomas** [comment]
Nice catch ! Thanks for looking into this. I was planning to get rid of FocusAllocationListener in favour of "focus created" and "focus destroyed" events:
https://github.com/jitsi/jicofo/blob/master/src/main/java/org/jitsi/jicofo/FocusManager.java#L325
https://github.com/jitsi/jicofo/blob/master/src/main/java/org/jitsi/jicofo/FocusManager.java#L396
Unfortunately we're not using that code, so it may take a lot of time before that happens, but we would appreciate a PR that does that !

**Comment by dihedral** [comment]
i am also running into this issue.
Thre behaviour is that the conference is not removed from the HashMap in the REST part of the code, and thus, when the room should be recreated, the reservation system is not queried
see [RESTReservations.java#L207](https://github.com/jitsi/jicofo/blob/master/src/main/java/org/jitsi/impl/reservation/rest/RESTReservations.java#L207)

**Comment by bahadorraha** [comment]
Hi,
I also ran into this problem:
When the conference duration limit is exceeded, jicofo removes the it from the conference map but when someone tries to start this terminated conference again, no request is sent to reservation system and the conference starts without reservation system being informed!

I had an ambiguity about expected behavior of reservation system:
Why Jicofo destroys XMPP MUC room only when duration limit is exceeded and not when everyone leaves the conference?
Does the reservation system should delete its record from its database immediately after receiving DELETE request from jicofo, or wait until its duration limit is exceeded and then delete the related record?
 
Any further works on this problem is appreciated :)

**Comment by bahadorraha** [comment]
Hi,
I also ran into this problem:
When the conference duration limit is exceeded, jicofo removes it from the conference map but when someone tries to start this terminated conference again, no request is sent to reservation system and the conference starts without reservation system being informed!

I had an ambiguity about expected behavior of reservation system:
Why Jicofo destroys XMPP MUC room only when duration limit is exceeded and not when everyone leaves the conference?
Does the reservation system should delete its record from its database immediately after receiving DELETE request from jicofo, or wait until its duration limit is exceeded and then delete the related record?

Any further works on this problem is appreciated :)

**Comment by hakimeh** [comment]
Hi,
I also ran into this problem:
When the conference duration limit is exceeded, jicofo removes it from the conference map but when someone tries to start this terminated conference again, no request is sent to reservation system and the conference starts without reservation system being informed!

I had an ambiguity about expected behavior of reservation system:
Why Jicofo destroys XMPP MUC room only when duration limit is exceeded and not when everyone leaves the conference?
Does the reservation system should delete its record from its database immediately after receiving DELETE request from jicofo, or wait until its duration limit is exceeded and then delete the related record?

Any further works on this problem is appreciated :)

**Comment by NeoN0x** [comment]
Hi,

I'm having the same behaviour, it is unexpected to be able to join a deleted conference.

I'm expecting the DELETE request to "delete" the conference. Any attempt to access it again should IMO result in another post request.

**Comment by paweldomas** [comment]
I'm not looking on any of those issues and have no plans to do so in the near future. If you have a problem the fastest way would be to submit a patch.

**Comment by damencho** [comment]
@NeoN0x I'm planning to look into this in the near future: https://github.com/jitsi/jitsi-meet/pull/8386
And merge it and when that is done we will deprecate the one in jicofo and will drop it at some point. So you better try that one, if you see problems with it we can fix them ...

**Comment by bgrozev** [comment]
Reservations are moved to a prosody module
