### ISSUE TITLE
Question about potential issue with Colibr2's transport update

### ISSUE THREAD

**Issue by ruozhen-vsee** [jitsi/jicofo#917]
Jicofo 7210 switched to use Colibri2 protocol to communicate between Jicofo/JVBs
One change between Colibri1/Colibri2 is the transport update code within updateParticipant function.

For Colibri1, it merge the existing transport together with the new one
https://github.com/jitsi/jicofo/blob/stable/jitsi-meet_7001/src/main/kotlin/org/jitsi/jicofo/conference/colibri/v1/ColibriV1SessionManager.kt

```
if (transport != null) {
val existingTransport = participantInfo.transport
  if (existingTransport == null) {
    participantInfo.transport = transport
  } else {
    TransportSignaling.mergeTransportExtension(existingTransport, transport)
  }
}
```
And for Colibri2, it simply replace the existing transport with the new one
https://github.com/jitsi/jicofo/blob/stable/jitsi-meet_7287/src/main/kotlin/org/jitsi/jicofo/conference/colibri/v2/Colibri2Session.kt
```
if (transport != null) {
  endpoint.setTransport(Transport.getBuilder().setIceUdpExtension(transport).build())
}
```

Is there any specific reason to make above change? From lib-jitsi-meet side,
https://github.com/jitsi/lib-jitsi-meet/blob/master/modules/xmpp/JingleSessionPC.js
Seems it might potentially send multiple transport-info message to Jicofo
```
/**
* The time duration for which the client keeps gathering ICE candidates to be sent out in a single IQ.
* @type {number} timeout in ms.
*/
const ICE_CAND_GATHERING_TIMEOUT = 150;
```

```
if (this.dripContainer.length === 0) {
  setTimeout(() => {
  if (this.dripContainer.length === 0) {
    return;
  }
  this.sendIceCandidates(this.dripContainer);
  this.dripContainer = [];
}, ICE_CAND_GATHERING_TIMEOUT);
}
```

And if Jicofo receive multiple transport-info messages uses Colibri2, it will update the endpoint's transport to only contain the ice candidates from the latest message which might potentially causes connectivity issues as some ice candidate will not be used?

**Comment by bgrozev** [comment]
Sorry @ruozhen-vsee, I didn't see your question earlier!

When the bridge receives a transport update it doesn't replace the candidates that have already been signaled, [it just adds the new ones](https://github.com/jitsi/jitsi-videobridge/blob/master/jvb/src/main/kotlin/org/jitsi/videobridge/transport/ice/IceTransport.kt#L174). In most cases the remote candidates are not needed at all because unless the bridge is behind a certain type of NAT it will discover them as "peer reflexive" candidates when it receives STUN binding requests from them.

So, while the code may be a little confusing I don't think it can lead to connectivity issues.

**Comment by ruozhen-vsee** [comment]
Thanks for the reply !
Agree that if videobridge side adds the new ice candidates then it shouldn't cause any connectivity issues
